server:
  port: 9100

dubbo:
  registry:
    address: 47.105.72.216:2181
    protocol: zookeeper
    id: dubboProductServer
    client: curator
  metadata-report:
    address: zookeeper://47.105.72.216:2181
  application:
    name: hanfu-product-cosumer
  protocol:
    id: dubbo
    name: dubbo
  consumer:
    client: netty4
    #

logging:
  file: ./target/king-words.log  
